### ISSUE TITLE
Load testing for email blasts

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/nonprofit-email-service#26]
As a user, I can simulate sending thousands of emails without actually sending them so that I can understand how quickly they will be delivered and verify there aren't any technical issues that will interfere with my email blast. 

Note that this will be essential for us to be able to improve the performance of the emailing engine.

**Comment by CodeNonprofit** [comment]
This might be helpful place to start for the person who tackles this: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/mailbox-simulator.html
