### ISSUE TITLE
White Label URLs (CNAME)

### ISSUE THREAD

**Issue by CarlJKashnier** [freeCodeCamp/nonprofit-email-service#27]
As a user I can set up a CNAME on my web server and use my domain to in place of the app server address.

Looks like 
`<a href="http://www.mydomain.com/ref=uniqueID&http://www.freecodecamp.com"> Link </a>`

instead of  
`<a href="https://awesome-pines-8675309.herokuapp.com/ref=uniqueID&http://www.freecodecamp.com"> Link </a>`

**Comment by AndrewGHC** [comment]
Hey Carl, could I ask for clarification on this one? My understanding is that CNAME records point to A records and are provided to DNS resolvers to offer the flexibility of multiple domains without the hassle of updating the host ip of each record. Would you be able to let me know how this one could be implemented in this app?

**Comment by CarlJKashnier** [comment]
Just coming off a hackathon, so forgive my for spelling. And ooor grammer.

When we send a link in an email: we want to enable the non-profit to change
the name from heavy-tacos-345627.herokuapp.com to mydomain.com so it would
be an account level setting. With the same /followlink/unique-id to show
click throughs was the orignal idea here.

The end user has to set this on their hosting. But we also need to add this
to the link forming software.

On Oct 23, 2016 6:37 PM, "AndrewGHC" <notifications@github.com> wrote:

Hey Carl, could I ask for clarification on this one? My understanding is
that CNAME records point to A records and are provided to DNS resolvers to
offer the flexibility of multiple domains without the hassle of updating
the host ip of each record. Would you be able to let me know how this one
could be implemented in this app?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FreeCodeCamp/nonprofit-email-service/issues/27#issuecomment-255619641>,
or mute the thread
