### ISSUE TITLE
API (Security)

### ISSUE THREAD

**Issue by CarlJKashnier** [freeCodeCamp/nonprofit-email-service#36]
As a developer I will have a secret code so that my mailing list will be secure.

**Comment by AndrewGHC** [comment]
Current plan is to check this against the OWASP top ten - https://www.owasp.org/index.php/OWASP_Top_Ten_Cheat_Sheet. 

- [ ] Injection
- [ ] Session management
- [ ] XSS cross site scripting vulnerabilities
- [ ] Insecure direct object references
- [ ] Security misconfiguration
- [ ] Sensitive data exposure
- [ ] Function level access control
- [ ] Cross site request forgery
- [ ] Libraries with known vulnerabilities
- [ ] Unvalidated redirects and forwards
