### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by jmavasa** [FreeCodeCamp/nonprofit-email-service#59]
is there any how to install document

**Comment by AndrewGHC** [comment]
Hi there,

It's a bit complex at the moment, but we'll streamline the process in the near future. For the current build you can do the following (it will require a local Postgres database and Google consumer keys):

1. Clone/download the app as normal
2. Run 'npm install' in the root directory

Finally - set up a Postgres database and pass environment variables to the app accordingly. You can do this by creating a file called '.env' in the root directory with the variables below. You'll also need to pass in Google auth credentials.

GOOGLE_CONSUMER_KEY
GOOGLE_CONSUMER_SECRET
PSQL_USERNAME
PSQL_PASSWORD
PSQL_DATABASE
